Default: &defaults
  database: fileedit-logkeeper.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: fileedit-logkeeper_test.sqlite3
  <<: *defaults

Staging:
  database: fileedit-logkeeper_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: fileedit-logkeeper_production.sqlite3
  poolsize: 100
  <<: *defaults
